"""initial migration

Revision ID: 97064f736275
Revises: 
Create Date: 2026-09-05 17:47:00.289017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97064f736275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_domain', ['user_id', 'domain_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_domain', type_='unique')
    # ### end Alembic commands ###